trigger:
  branches:
    include:
      - class_preparation   # O pipeline será acionado quando houver mudanças nessa branch

pool:
  vmImage: 'ubuntu-latest'  # Define o sistema operacional da máquina virtual usada no pipeline

variables:
  pythonVersion: '3.12.4'  # Define a versão do Python a ser usada

steps:
# Configura a versão do Python no ambiente
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(pythonVersion)
    addToPath: true

# Instala as dependências do projeto
- script: |
    python -m pip install --upgrade pip  # Atualiza o pip para a versão mais recente
    pip install -r requirements.txt  # Instala os pacotes listados no requirements.txt
  workingDirectory: ./login-app  # Define o diretório correto onde está o arquivo requirements.txt
  displayName: 'Instalar dependências'
